### ISSUE TITLE
Remove div from base.html for content that does not require sidebar navigation

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#129]
In base.html, we have space reserved on the side (block is called side_block) that is intended for pages that have the sidebar (for year selection). However, pages like home and index don't need that space reserved. It is preventing the page content from starting near the left side of the page.

One possible solution is to put {% if <condition> %}...{% endif %} template directives around the <div> tag that encloses the side_block block.

It appears that all of the views that have side_block content, add 'side_block_content' to the context variable passed to the render function. So the condition above might be as simple as {% if side_block_content %}...{% endif %}. For views that don't need the side_block block, that condition will fail and the <div> tag will be suppressed.

I did some simple testing and found that most pages were ok. However the player_results page no longer had the sidebar. I wasn't able to figure out easily how the year_sidebar render got into that block. Can you explain?

**Comment by jbholden** [comment]
Sorry for the late reply, I just now read this issue.

I believe that the issue is related to the memcache.  The overall results page and the week results page use the memcache, while the player results page does not use the memcache.  

The pages that use caching render the sidebar from the year_sidebar.html template within the python code (passing in the year and years_in_pool parameters), and then save that rendering into the side_block_content in the memcache.  This rendered content string is just inserted "as is" when generating the page.

```
from overall_results.html:
{% block side_block %}
    {{ side_block_content|safe }}
{% endblock %}
```

Since player results does not use the memcache, then that page sets the years_in_pool and year parameters each time the page is created, and this forms the sidebar from those variables.

```
from player_results.html
{% block side_block %}
    {% include "pick10/year_sidebar.html" %}
    {% endblock %}

from year_sidebar.html
<ul class="nav nav-pills nav-stacked">
    {% for year_num in years_in_pool %}
        {% if year == year_num %}
            <li class="active"><a href="{% url 'overall_results' year_num %}">{{year_num}}</a></li>
        {% else %}
            <li><a href="{% url 'overall_results' year_num %}">{{year_num}}</a></li>
        {% endif %}
    {% endfor %}
</ul>
```

**Comment by blreams** [comment]
Now that I've been digging around in the results generation code, I probably could've figured this out. But thanks for the insight. I'll make some tweaks to my change that is in flight and hopefully reclaim that blank space on the left for pages like the landing page.

**Comment by blreams** [comment]
In addition to what was discussed above, I also modified the player results view to generate the sidebar content (same way as is done for the overall and week results pages).

Changes committed and deployed to pythonanywhere.
