### ISSUE TITLE
User is logged out when visiting cached pages

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#40]
I ran into a little problem with memcache...at least I think it is due to memcache. If you are a logged in user and you navigate to any of the cached pages, it seems as though you get logged out. I haven't really characterized this issue fully.

**Comment by jbholden** [comment]
This is probably because the entire page is getting cached when it is calculated.  As a result, the user that is logged in at the time the page is cached effects what user shows up in the page.

I observed that when going from the update games page to the update pages page, the user is logged out.  Since no user is logged in when the page is calculated for the memcache, subsequent accesses to the page will not show a user.

I think the fix is to change what gets stored in the memcache.  It should save almost the entire page (except for the bar across the top with the user info), and then render a page from this instead of just returning the entire page from the memcache.

**Comment by jbholden** [comment]
I think the reason the user is logged out in the update page is because the page is created with render_to_string without request being passed in instead of the render function.

```Python
# from views.py
def update_pages(request,year,week_number):
    if request.method == "GET":
        response = UpdatePageView().get(year,week_number)
        return response
    return HttpResponseNotFound('<h1>Page not found</h1>')

# from update_view.py
def get(self,year,week_number):
    data={'year':year,'week_number':week_number}
    html = render_to_string("pick10/update_pages.html",data)
    return HttpResponse(html)

# fix update_view.py by using render
def get(self,request,year,week_number):
    data={'year':year,'week_number':week_number}
    return render(request,"pick10/update_pages.html",data)
```

The mentioned fix should fix the logout issue, but I believe the problem of caching the entire page (mentioned in prior comment) is also still an issue.

**Comment by blreams** [comment]
That's a good catch. I made the above fix and it doesn't log me out anymore (though the results pages appear as logged out because of the cached entry as you mentioned).

But there is a more subtle issue. I don't think you can cache just one view of the results...you'd have to cache both the public and private views...and return the appropriate one from the cache depending on the logged state of the user.

For now, I will commit this change and close the issue. Then I will open a new issue for the results caching.
