### ISSUE TITLE
How to handle picks when player defaults

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#47]
When a player defaults in a week, I believe the code requires that there still be picks for the player but the winner field will be equal to 0 instead of 1 or 2 (for team1/team2).  I'm not exactly sure that this is correct, but I know that this method works.

The question then is when to create the picks for a defaulting player.  The following is possible methods to do this.
* method 1:  When a new week is created, create picks for every player with winner=0
* method 2:  After the pick deadline, create picks for every player that defaults

There is a slight complication with method 1 when the pool initially starts for a year.  I assume that users can sign up for the year at the same time that already signed up users are making picks.  Therefore, if a player signs up and games are available, then the picks with defaults for that player need to be created at that time.  This might also be an issue if players are allowed to sign up in week 2 or later.

**Comment by blreams** [comment]
In the scoring spreadsheet, the commissioner would manually fill in defaulters with picks that equaled the worst actual picks of the week.

Does calculator automatically set a defaulting player's score to the lowest score of the week?

I don't think we ever had this happen, so there is no precedence for it. So what do we do if a player only makes a subset of picks (ie. makes picks for some but not all games)?

**Comment by jbholden** [comment]
Any game where a player does not pick will be counted as a loss.  I don't think that the enter picks page POST method will accept picks unless there are picks for games 1-9 and scores for game 10.

**Comment by blreams** [comment]
I feel as though there is still an outstanding issue here. Let me give you my take on what I think we can do to mitigate this.

The open issue is that we don't handle default picks because we don't know before the games are played what the lowest score is going to be.

Let's say that we don't create default picks for every Player at the beginning of the week. Which means that when the pick deadline arrives, there may be Players that have not submitted picks. There is really only one remaining time that the commissioner will administer the current week...and that is to lock_scores.

So, the commissioner goes into the admin and sets lock_scores on the Week object. Then the commissioner proceeds to enter or confirm the final scores for all the games. How is that done? Right now it looks like the commissioner has to GET the pick10/<year>/week/<weeknum>/games URL. The resulting form has an unlock button that I presume only the commissioner can activate. Then the commissioner can set the final scores and click on the Lock Scores button. Does that POST the form with modified scores? If so, we could use the fact that the form was posted with scores locked by a commissioner and call a special routine that would generate default picks for any Players that didn't have picks...which would require another calculate.

Does that make sense?

I mean we can always rely on the admin interface. Using that a commissioner could modify the scores, and could even generate default picks.

**Comment by jbholden** [comment]
Right now, the update games lock button just sets the week.locks_scores to True and then redirects to the update games page again.  I guess the procedure is to enter the scores, submit, then revisit the page and locks the scores.

I think the issue with missing picks might prevent some pages from working after the pick deadline has passed.  So generating the picks when locking the scores wouldn't work.  They would have to be generated when the pick deadline passes.  I'm not 100% sure this is right.  I will need to investigate it a little bit.

**Comment by jbholden** [comment]
A player that does not have picks in the database should not cause any problems and be treated as a default for that week.  see #89 

So, we can just leave out the player's picks for a week, or for completeness we could generate picks for a defaulting player with winner=0 at the end of a pool week.

**Comment by blreams** [comment]
Closing this issue.
