### ISSUE TITLE
Whitespace above body_block in new base.html

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#51]
With the recent changes to base.html, I am seeing the following picture.  For some reason there is a bunch of whitespace above the "College Football Pick 10" text.  Do you know what might be causing this?

![screen shot 2015-08-19 at 6 23 43 pm](https://cloud.githubusercontent.com/assets/1541768/9370614/9abb628e-469f-11e5-8311-c66bd77f5edf.png)

**Comment by jbholden** [comment]
Using the web inspector in safari, it appears that the content is getting put below the end of the sidebar.

**sidebar highlighted**
![screen shot 2015-08-19 at 6 32 51 pm](https://cloud.githubusercontent.com/assets/1541768/9370771/d0468ab8-46a0-11e5-84a7-9f608aa12975.png)

**body highlighted**
![screen shot 2015-08-19 at 6 33 03 pm](https://cloud.githubusercontent.com/assets/1541768/9370772/d32f2c9e-46a0-11e5-9d63-b99bfab3ef66.png)

**Comment by jbholden** [comment]
It gets worse when there are more years in the sidebar.

![screen shot 2015-08-19 at 7 20 45 pm](https://cloud.githubusercontent.com/assets/1541768/9371994/771cf25e-46a7-11e5-81e3-f951e81b19bc.png)

**Comment by jbholden** [comment]
I replaced the sidebar (rendered from templates/pick10/year_sidebar.html) with just a bunch of text within div tags and still saw the problem.  So I don't think the problem is from year_sidebar.html.

![screen shot 2015-08-19 at 7 22 51 pm](https://cloud.githubusercontent.com/assets/1541768/9372033/e5fe9a1a-46a7-11e5-9abf-386adc04e2b2.png)

**Comment by blreams** [comment]
I don't know what is going on with the whitespace above the navbar. I actually don't see it...but then I am not using Safari. I did make a change in base.html in my createnewweek branch where I call for bootstrap collateral from static instead of pulling it from getbootstrap.com. I did this because I was having some transient issues accessing getbootstrap.com. Could be a version-itis thing.

If you want I can generate a pull request for my createnewweek branch and let you see if that helps your issue. If so, I don't have a problem committing what I have now to master. I'm just going to continue development on the createnewweek branch.

As for the sidebar issue, let's track that as a separate issue because I don't think it is related. There may be something we are doing wrong with the way the sidebar <div> or body <div> is specified.

**Comment by blreams** [comment]
I finally figured out what was going on regarding the extra white space above the navbar. Apparently it has to do with this line in templates/base.html:

```
<link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
```
That line has been removed and was committed to master when I merged createnewweek. So I am going to close this Issue. I'm also going to open a new Issue for the sidebar.
