### ISSUE TITLE
Can't get enter_picks URL to work

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#58]
I couldn't get in to the enter_picks URL:

![image](https://cloud.githubusercontent.com/assets/5880937/9426624/73db04ce-491c-11e5-830b-2f048673fae7.png)

As you can see, it gave me the error message saying "The week is currently in progress. No picks can be made."

Here is a snapshot of the admin showing the 2015 Week 1 settings:

![image](https://cloud.githubusercontent.com/assets/5880937/9426614/a0b4ee5c-491b-11e5-91f6-68d2c62b04fb.png)

The current date/time is 8/22 at 22:15 so lock_picks has a future setting.

I did link the UserProfile to the Player, so I'm not sure what else I need to do.

Not sure if this has any bearing on the issue, but I did have to go into the shell and manually pull my Player object to get the Player.id so I could enter it in the URL. I'm thinking that should automatically fill in when I view the results pages, but I wasn't getting the "Enter picks" link in the navbar.

**Comment by blreams** [comment]
BTW, I did create a PlayerYear object.

**Comment by jbholden** [comment]
The week needs to be in the "not_started" state in order to enter picks.  Look at the games for 2015 week 1 in the database and verify that the game_state is set to 1 for all the games (i.e NOT_STARTED).

Did you use the update games page to clear out the scores and uncheck all the final?
If so, there might be some issue with the update games page.

**Comment by blreams** [comment]
Looks like that worked. I'll close the issue.
