### ISSUE TITLE
Need way to determine if User has registered

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#7]
The users will be initially created by using the pool spreadsheets from past years.  These users are unregistered initially.  When a user logs in for the first time, they will then need to register themselves, which means associating their identity with a specific User model from a past year, or creating a new User model.  Shouldn't the User model somehow indicate if a user is registered or unregistered?

A couple of ideas
```
Option 1:  Add a boolean flag called something like 'registered' to the UserProfile model
Option 2:  Use the django User.is_active flag?
Option 3:  something else?
```

**Comment by jbholden** [comment]
I believe the is_active flag is used by the registration module.  When the user creates an account, an email is sent to the user and once he/she clicks the link, is_active will be set to True.
https://django-registration-redux.readthedocs.org/en/latest/quickstart.html

I don't know if this flag could be used or not to determine if user has registered.  I'm still trying to figure out how to create an unregistered user #4 from the pool spreadsheet.

**Comment by jbholden** [comment]
I apologize if this issue is getting to long, but I think the real issue here is how to distinguish between users that have signed up for the site and users loaded from the spreadsheet that may not be signed up for the site yet.

Perhaps another option would be to create a Player model for every player (which I used in the google version) and a User model that represents registers users, and then point to a player class.

```
class Player(models.Model):
    name = models.CharField()
    years = # list of integers

class UserProfile(models.Model)
   player = models.OneToOneField(Player)
   ... other fields
```

What are your thoughts on how to represent unregistered users loaded from the spreadsheet?

**Comment by blreams** [comment]
Actually, I think there are 3 user states.

1. (entered) A user that has been created from an historical spreadsheet, but has not registered with the site. This user is simply a placeholder so that previous pool years' history can be shown. There is no need for a user in this state to login.

2. (registered) This is a user that has registered with the site some time in the past but is not actively participating in the current year's pool. This user will have full login privileges to see anything that is going on with the pool. The restriction is that they cannot enter picks in the current pool.

3. (active) This is a registered user that is actively particpating in the current year's pool. They have paid the entry fee and are able to enter picks for each week of the year.

How might this fit in with the Player and User models? Maybe the best thing is to create a Player model entry for every user (entered, registered or active). 

When you create a Player from the historical spreadsheet, they don't need an entry in the User model (and hence they don't need a username/password). They can't login. But because they are in the Player model they can appear in any historical representations of pool data.

That means the only users in the User model are registered or active users. When they first register with the site, they are considered registered, but not active. I think we can use the is_active flag to distinguish registered and active. A user goes from registered to active when they pay the entry fee. The admin will then set their is_active flag. At the end of the pool season, every active user get reset to registered in preparation for the following year.

The only question is how to associate a registered or active user to an existing Player model entry vs. creating a new Player model entry. I think by its nature it is a manual process that the admin will have to perform at the time of registration. But it would be one or the other.

**Comment by jbholden** [comment]
Would the registration process still send a confirmation email that sets the is_active flag?  Or would there be code to override this functionality?

Would the final result look something like this?
```Python
# create a single player for each user.  The player is created when loading past years
# or a new player is created when a user that has not been in the past is registered
Player:
  state = CharField()                          # entered,registered or active
  public_name = CharField()                    # name showed to not logged in users
  private_name = CharField()                   # name showed to logged in users
  years = models.CommaSeparatedIntegerField()  # list of years in pool

# when a new user registers, it is associated with 
# an existing player or a new player is created
UserProfile:
  player = models.OneToOneField(Player)
  ...
```

Or should the player/user state be inferred from the User, is_active flag, and Player models?

**Comment by blreams** [comment]
Since the User model already has the is_active flag along with functions for the admin to set/clear/test the flag, why don't we use Player.state to distinguish whether a Player has a link to a UserProfile. Then the User.is_active flag can distinguish registered vs. active. Does that make sense?

So, a Player() will be created for every unique instance in the history spreadsheets. And initially, Player.state for each can be set to 'entered'. Actually, since there  are only two "states" for a Player, why not use a boolean flag (like Player.is_registered). Then when a Player is first created from the history spreadsheet, set Player.is_registered = False.

When it comes time to start the pool in the Fall, everyone that is planning to participate will go through the registration process. We'll need a method that the admin can call for every new registration, that will do one of two things:

1. If the UserProfile corresponds to a Player that was pulled in from history, then it should link the UserProfile to the existing Player.
2. If the UserProfile is for a new (no history) participant, then a new Player must be created followed by linking the UserProfile to that new Player.

The end result is that every UserProfile will have a link to a Player (either a new one, or one created from history).

**Comment by jbholden** [comment]
This method seems ok to me.

**Comment by blreams** [comment]
I'm going to assign myself to this one and start implementing the Player model.

**Comment by blreams** [comment]
I created models for Year, Player, and PlayerYear. The Year model will have a row for each year of the pool. It will be used to store attributes about each year's pool (entry fee, weekly payout, payouts for first, second and third place).

The Player model will be as discussed above (basically a way to capture the unique name for each player in the pool spreadsheets).

The PlayerYear model will be a cross-product of the Year and Player models...each player will have a unique row for each that they participate(d) in the pool.

I also made a number of changes to other models to consolidate things like year number, week number and game number.
