### ISSUE TITLE
Setting favorite team in UserProfile did not work

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#84]
When I used the admin interface to set the favorite team, it failed with this message

```
Cannot assign "u'124'": "UserProfile.favorite_team" must be a "Team" instance.
```
I went to the /admin url, then clicked User, and then tried to assign "Georgia Tech" to the "Favorite Team" field.

I'm not sure if I'm doing something wrong or not, but it appears that this format it not quite right.  Maybe team instead of team.id?
```
fav_choices = [(team.id, team.team_name) for team in Team.objects.all()]
```

**Comment by blreams** [comment]
I'm not sure we ever need to assign the favorite_team field via the admin interface. Each User can just click on the Profile button in the navbar (it only appears for logged in Users) and set their profile preferences (company, preferredtz, and favorite_team).

There appears to be something about using a forms.ModelForm object for the form. When you do this a bunch of stuff happens behind the scenes, including needing a team.id to specify the team.

While I agree that the admin interface doesn't work to set this particular field, I don't think it is a big problem either.

BTW, I struggled a good bit to get this working...including trying the fav_choices that you suggested above, but I couldn't get it work. I may spend some more time on this later.

**Comment by blreams** [comment]
OK, I overhauled the favorite_team field in UserProfile. Instead of using a ForeignKey field, I used a CharField and added a custom validator to the form object to insure that no one can post a favorite_team string that is not a valid team_name in the Team model.

This addresses two Issues. First of all, the admin interface can now set the favorite_team field successfully (although, I find it klunky because the teams are not ordered alphabetically). Secondly, there is no need to update any UserProfiles when the Team model changes (ie. Team.id numbers are different).

I committed this directly to master. But it includes another db migration, so you will need to run:
```
python manage.py migrate
```
