### ISSUE TITLE
2007 week 4 imported data from excel causes exception

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#87]
Here is the exception:

![image](https://cloud.githubusercontent.com/assets/5880937/9675713/36090a02-528f-11e5-9c2c-78d8dd49262f.png)

I believe the problem is because there is no clear winner from the game 10 tie-breaks since both players had the same score for game 10. I believe we broke the tie by choosing the player that had submitted their picks earlier...but I don't remember who that was. I'll see if I can dig up that info.

Does this mean the tie-break code does not take into account the pick updated timestamp to break the tie?

Also, once I figure out who the winner is, I can modify the spreadsheet to force a clear winner by changing one of those Players' tie-break score. Any reason why I shouldn't do that...just so we don't run into this ambiguity again?

**Comment by jbholden** [comment]
I think you are looking at week 6 in the 2007 excel spreadsheet (I accidentally used that sheet too at first).  

**Issue 1:  submit times tiebreak**
If you take a look at the tiebreak page for week 6, it states that it cannot determine the winner because it does not have the submission times.  However, if you look at the week 6 results page, it selected Johnny as the winner.  I believe this is because I wasn't expecting more than 1 winner in the spreadsheet.

**Issue 2:  week 4 exception**
If I remove this assertion, this is what the week results page looks like.

![screen shot 2015-09-03 at 11 26 45 pm](https://cloud.githubusercontent.com/assets/1541768/9676116/e74efb3c-5294-11e5-9904-2a6e179d1ee8.png)

This problem is that it has calculated Scott having more wins that the other players, so Scott should have won.  However the spreadsheet specified that Chip won.  Here are Scott's picks for the week.

![screen shot 2015-09-03 at 11 30 04 pm](https://cloud.githubusercontent.com/assets/1541768/9676137/3345eb2c-5295-11e5-8cd4-37ff998ff76b.png)

I cross checked his picks with the spreadsheet and I believe the picks match his picks.
If you look at the spreadsheet though, 2 rows are grayed out.  Does this mean those games didn't count?
Scott loss the first grayed out row, and won the 2nd grayed out row.  If you remove this win, Scott would have 7 wins and not 8 wins.

![screen shot 2015-09-03 at 11 41 44 pm](https://cloud.githubusercontent.com/assets/1541768/9676154/5ce033b6-5295-11e5-8727-594157c7fe87.png)

**Comment by blreams** [comment]
Just to clarify, for Issue 1, do you have code to break ties when there are submission times for picks? If so, are you using the updated_by field for a Player's Picks? And if that is case, then I suppose you have to select one of the ten Picks for the Week and use that Pick's updated_by value...do you select game 10?

For issue 2, which is the cause of the exception...something unusual happened that week, but I can't remember exactly what is was. I'll have to see if I can dig up the results email from that week, but I do know that for whatever reason the commissioners huddled and decided that the only fair thing to do was to throw out those two games (the grayed out ones). Which is why the winner column in the spreadsheet shows no winner in either of those games.

Regardless of why those games were dropped, it seems as though I need to modify the spreadsheet in such a way to insure that Chip is the actual winner (in points and by the winner box). I suppose I could change everyone's picks such that no Players get those games correct.

**Comment by jbholden** [comment]
**Issue 1:**
Yes, there is code that breaks ties by the player submission time.  

```Python
pick10/week_winner.py __calculate_tiebreaker_3()   # calculates the tiebreak
pick10/calculator.py get_player_submit_time()  # gets the submit time
```
The submit time for a player is calculated by looking at the pick.created time and the pick.updated time in each of the player's 10 picks for that week, and return the time that is the latest of all of those.

**Issue 1 - multiple winners**
There is still an issue with there being multiple winners in the spreadsheet for week 6.  The week results page shows only 1 winner.  This is because it doesn't expect multiple winners selected in the spreadsheet.

**Comment by jbholden** [comment]
Would it be better to add a submit_time field to the Picks model and use that instead?  It could get set every time the enter picks page POST method is submitted.  Using the modified and created time could run into problems if those Pick instances are ever modified for some reason in the future.

**Comment by blreams** [comment]
That sounds like a reasonable idea. What do you think about setting up this field such that it can be null in the DB? That would minimize the impact of migrating as well as not requiring any change to stage_history.py.

**Comment by jbholden** [comment]
Yes, a null value would be great.  Past years would be set to null because we don't know the submit times.  Only future picks would get a submit time.

**Comment by jbholden** [comment]
As a fix for issue 1 (i.e. multiple winners in spreadsheet), I created code to set the winner to None if multiple winners are in the spreadsheet.  As a result, the pool calculates the winner for the week instead of using the Week.winner field.  See #90

**Comment by blreams** [comment]
I just did a commit to master to add submit_time to the Pick model. I also modified the 2007 spreadsheet such that all players had incorrect picks in the two aborted games in week 4.

Before closing this issue, I need for you to change the enter picks POST to set submit_time.

**Comment by jbholden** [comment]
When setting the submit time, I get the following warning if I just set it to datetime.now()
```Python
RuntimeWarning: DateTimeField Pick.submit_time received a naive datetime 
(2015-09-11 23:23:04.005125) while time zone support is active.
```

If I localize it to Eastern time, then I don't get this warning.  

My question is, how will we know what timezone the server is running in on PythonAnywhere?  Can we use the TIME_ZONE variable in collegefootballpick10/settings.py?  Does this ensure it will run in an Eastern time zone?

**Comment by jbholden** [comment]
I think I have a solution.  The following gives the time in UTC.  I believe it will work based on whatever timezone the server is in.
```Python
pick.submit_time = dt.datetime.now(pytz.timezone('UTC'))
```

**Comment by blreams** [comment]
As I understand it, django will always store DateTime objects in the database as UTC (Universal Coordinated Time). But It can only do that if it is given a non-naive DateTime object (ie. it comes with a time zone).

Given that, I think we might need to run some experiments. When I run the date command from a bash console on the website, it comes back as UTC. If I start a django python shell (python manage.py shell) and then run "import django.utils.timezone as tz; tz.now()" I also get a UTC DateTime.

We are not asking the Player to enter a DateTime, rather the DateTime is derived by getting it from python. As long as we ask for it using django.utils.timezone.now(), then UTC is probably the proper thing. And in the long run it may not matter. IOW, you get tz.now() and it is UTC. Even if you convert it to some other time zone and then store it the DB, django it going to covert it back to UTC.

The kicker is making sure that displayed DateTime objects are converted to the Players preferredtz.

**Comment by blreams** [comment]
I just saw your latest comment. I think we are saying the same thing. However, I would encourage you to use django.utils.timezone.now() to get DateTime objects. You can use pytz to convert those to other timezones.

**Comment by jbholden** [comment]
I changed the code to use django.utils.timezone.now().  Enter picks page now sets the submit_time.  The changes have been pushed to the master branch.

**Comment by blreams** [comment]
I think we can close this issue now.
