### ISSUE TITLE
Score for a defaulter in a week

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#97]
If a player defaults in a week, I have been assigning the defaulter a score of 0 for that week in the code.  However, I just read in the pool rules that the score should match the lowest score for that week.  Which is the behavior that is desired?

**Comment by blreams** [comment]
Giving a defaulting player a zero always seemed harsh, which is why we changed the rule (many years ago) to give a defaulting player a score equivalent to the lowest actual score for that week. That was back in the days when there were a lot fewer participants each year and the odds of anyone scoring a legitimate zero were vanishingly small. Now...not so much.

I'm OK with giving defaulting players a zero, especially with the pool being available online. There simply is no excuse for not making picks. Also, think about the logistics of scoring defaulting players based on completed scores once the games have been played. Probably not worth the effort.

**Comment by blreams** [comment]
Since this is what we are currently doing I am going to close this issue.
